# catpuccin

# colourful: true

# filekinds:
#   normal: {foreground: "#BAC2DE"}
#   directory: {foreground: "#89B4FA"}
#   symlink: {foreground: "#89DCEB"}
#   pipe: {foreground: "#7F849C"}
#   block_device: {foreground: "#EBA0AC"}
#   char_device: {foreground: "#EBA0AC"}
#   socket: {foreground: "#585B70"}
#   special: {foreground: "#CBA6F7"}
#   executable: {foreground: "#A6E3A1"}
#   mount_point: {foreground: "#74C7EC"}

# perms:
#   user_read: {foreground: "#CDD6F4"}
#   user_write: {foreground: "#F9E2AF"}
#   user_execute_file: {foreground: "#A6E3A1"}
#   user_execute_other: {foreground: "#A6E3A1"}
#   group_read: {foreground: "#BAC2DE"}
#   group_write: {foreground: "#F9E2AF"}
#   group_execute: {foreground: "#A6E3A1"}
#   other_read: {foreground: "#A6ADC8"}
#   other_write: {foreground: "#F9E2AF"}
#   other_execute: {foreground: "#A6E3A1"}
#   special_user_file: {foreground: "#CBA6F7"}
#   special_other: {foreground: "#585B70"}
#   attribute: {foreground: "#A6ADC8"}

# size:
#   major: {foreground: "#A6ADC8"}
#   minor: {foreground: "#89DCEB"}
#   number_byte: {foreground: "#CDD6F4"}
#   number_kilo: {foreground: "#BAC2DE"}
#   number_mega: {foreground: "#89B4FA"}
#   number_giga: {foreground: "#CBA6F7"}
#   number_huge: {foreground: "#CBA6F7"}
#   unit_byte: {foreground: "#A6ADC8"}
#   unit_kilo: {foreground: "#89B4FA"}
#   unit_mega: {foreground: "#CBA6F7"}
#   unit_giga: {foreground: "#CBA6F7"}
#   unit_huge: {foreground: "#74C7EC"}

# users:
#   user_you: {foreground: "#CDD6F4"}
#   user_root: {foreground: "#F38BA8"}
#   user_other: {foreground: "#CBA6F7"}
#   group_yours: {foreground: "#BAC2DE"}
#   group_other: {foreground: "#7F849C"}
#   group_root: {foreground: "#F38BA8"}

# links:
#   normal: {foreground: "#89DCEB"}
#   multi_link_file: {foreground: "#74C7EC"}

# git:
#   new: {foreground: "#A6E3A1"}
#   modified: {foreground: "#F9E2AF"}
#   deleted: {foreground: "#F38BA8"}
#   renamed: {foreground: "#94E2D5"}
#   typechange: {foreground: "#F5C2E7"}
#   ignored: {foreground: "#7F849C"}
#   conflicted: {foreground: "#EBA0AC"}

# git_repo:
#   branch_main: {foreground: "#CDD6F4"}
#   branch_other: {foreground: "#CBA6F7"}
#   git_clean: {foreground: "#A6E3A1"}
#   git_dirty: {foreground: "#F38BA8"}

# security_context:
#   colon: {foreground: "#7F849C"}
#   user: {foreground: "#BAC2DE"}
#   role: {foreground: "#CBA6F7"}
#   typ: {foreground: "#585B70"}
#   range: {foreground: "#CBA6F7"}

# file_type:
#   image: {foreground: "#F9E2AF"}
#   video: {foreground: "#F38BA8"}
#   music: {foreground: "#A6E3A1"}
#   lossless: {foreground: "#94E2D5"}
#   crypto: {foreground: "#585B70"}
#   document: {foreground: "#CDD6F4"}
#   compressed: {foreground: "#F5C2E7"}
#   temp: {foreground: "#EBA0AC"}
#   compiled: {foreground: "#74C7EC"}
#   build: {foreground: "#585B70"}
#   source: {foreground: "#89B4FA"}

# punctuation: {foreground: "#7F849C"}
# date: {foreground: "#F9E2AF"}
# inode: {foreground: "#A6ADC8"}
# blocks: {foreground: "#9399B2"}
# header: {foreground: "#CDD6F4"}
# octal: {foreground: "#94E2D5"}
# flags: {foreground: "#CBA6F7"}

# symlink_path: {foreground: "#89DCEB"}
# control_char: {foreground: "#74C7EC"}
# broken_symlink: {foreground: "#F38BA8"}
# broken_path_overlay: {foreground: "#585B70"}



# tokiyo style

colourful: true

filekinds:
  normal: { foreground: "#c0caf5" }
  directory: { foreground: "#7aa2f7" }
  symlink: { foreground: "#2ac3de" }
  pipe: { foreground: "#414868" }
  block_device: { foreground: "#e0af68" }
  char_device: { foreground: "#e0af68" }
  socket: { foreground: "#414868" }
  special: { foreground: "#9d7cd8" }
  executable: { foreground: "#9ece6a" }
  mount_point: { foreground: "#b4f9f8" }

perms:
  user_read: { foreground: "#2ac3de" }
  user_write: { foreground: "#bb9af7" }
  user_execute_file: { foreground: "#9ece6a" }
  user_execute_other: { foreground: "#9ece6a" }
  group_read: { foreground: "#2ac3de" }
  group_write: { foreground: "#ff9e64" }
  group_execute: { foreground: "#9ece6a" }
  other_read: { foreground: "#2ac3de" }
  other_write: { foreground: "#ff007c" }
  other_execute: { foreground: "#9ece6a" }
  special_user_file: { foreground: "#ff007c" }
  special_other: { foreground: "#db4b4b" }
  attribute: { foreground: "#737aa2" }

size:
  major: { foreground: "#2ac3de" }
  minor: { foreground: "#9d7cd8" }
  number_byte: { foreground: "#a9b1d6" }
  number_kilo: { foreground: "#89ddff" }
  number_mega: { foreground: "#2ac3de" }
  number_giga: { foreground: "#ff9e64" }
  number_huge: { foreground: "#ff007c" }
  unit_byte: { foreground: "#a9b1d6" }
  unit_kilo: { foreground: "#89ddff" }
  unit_mega: { foreground: "#2ac3de" }
  unit_giga: { foreground: "#ff9e64" }
  unit_huge: { foreground: "#ff007c" }

users:
  user_you: { foreground: "#3d59a1" }
  user_root: { foreground: "#bb9af7" }
  user_other: { foreground: "#2ac3de" }
  group_yours: { foreground: "#89ddff" }
  group_root: { foreground: "#bb9af7" }
  group_other: { foreground: "#c0caf5" }

links:
  normal: { foreground: "#89ddff" }
  multi_link_file: { foreground: "#2ac3de" }

git:
  new: { foreground: "#9ece6a" }
  modified: { foreground: "#bb9af7" }
  deleted: { foreground: "#db4b4b" }
  renamed: { foreground: "#2ac3de" }
  typechange: { foreground: "#2ac3de" }
  ignored: { foreground: "#545c7e" }
  conflicted: { foreground: "#ff9e64" }

git_repo:
  branch_main: { foreground: "#737aa2" }
  branch_other: { foreground: "#b4f9f8" }
  git_clean: { foreground: "#292e42" }
  git_dirty: { foreground: "#bb9af7" }

security_context:
  colon: { foreground: "#545c7e" }
  user: { foreground: "#737aa2" }
  role: { foreground: "#2ac3de" }
  typ: { foreground: "#3d59a1" }
  range: { foreground: "#9d7cd8" }

file_type:
  image: { foreground: "#89ddff" }
  video: { foreground: "#b4f9f8" }
  music: { foreground: "#73daca" }
  lossless: { foreground: "#41a6b5" }
  crypto: { foreground: "#db4b4b" }
  document: { foreground: "#a9b1d6" }
  compressed: { foreground: "#ff9e64" }
  temp: { foreground: "#737aa2" }
  compiled: { foreground: "#737aa2" }
  build: { foreground: "#1abc9c" }
  source: { foreground: "#bb9af7" }

punctuation: { foreground: "#292e42" }
date: { foreground: "#e0af68" }
inode: { foreground: "#737aa2" }
blocks: { foreground: "#737aa2" }
header: { foreground: "#a9b1d6" }
octal: { foreground: "#ff9e64" }
flags: { foreground: "#9d7cd8" }

symlink_path: { foreground: "#89ddff" }
control_char: { foreground: "#ff9e64" }
broken_symlink: { foreground: "#ff007c" }
broken_path_overlay: { foreground: "#ff007c" }
