
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
live_config_reload = true

[font]
size = 12.0

[font.normal]
family = "jetBrainsMono Nerd Font"

[window]
opacity = 0.80
dimensions.columns = 80
dimensions.lines = 24
decorations = "full"
title = "My Alacritty Terminal"

[window.padding]
x = 10
y = 4

# [shell]
# program = "zellij"
# args = ["-l", "welcome"]
